(function() {var implementors = {};
implementors["brotli2"] = [{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html\" title=\"trait std::io::BufRead\">BufRead</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"brotli2/bufread/struct.BrotliEncoder.html\" title=\"struct brotli2::bufread::BrotliEncoder\">BrotliEncoder</a>&lt;R&gt;",synthetic:false,types:["brotli2::bufread::BrotliEncoder"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.BufRead.html\" title=\"trait std::io::BufRead\">BufRead</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"brotli2/bufread/struct.BrotliDecoder.html\" title=\"struct brotli2::bufread::BrotliDecoder\">BrotliDecoder</a>&lt;R&gt;",synthetic:false,types:["brotli2::bufread::BrotliDecoder"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"brotli2/read/struct.BrotliEncoder.html\" title=\"struct brotli2::read::BrotliEncoder\">BrotliEncoder</a>&lt;R&gt;",synthetic:false,types:["brotli2::read::BrotliEncoder"]},{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"brotli2/read/struct.BrotliDecoder.html\" title=\"struct brotli2::read::BrotliDecoder\">BrotliDecoder</a>&lt;R&gt;",synthetic:false,types:["brotli2::read::BrotliDecoder"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
