(function() {var implementors = {};
implementors["brotli2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"brotli2/raw/enum.CompressOp.html\" title=\"enum brotli2::raw::CompressOp\">CompressOp</a>",synthetic:false,types:["brotli2::raw::CompressOp"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"brotli2/raw/struct.Error.html\" title=\"struct brotli2::raw::Error\">Error</a>",synthetic:false,types:["brotli2::raw::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"brotli2/raw/enum.CoStatus.html\" title=\"enum brotli2::raw::CoStatus\">CoStatus</a>",synthetic:false,types:["brotli2::raw::CoStatus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"brotli2/raw/enum.DeStatus.html\" title=\"enum brotli2::raw::DeStatus\">DeStatus</a>",synthetic:false,types:["brotli2::raw::DeStatus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"brotli2/enum.CompressMode.html\" title=\"enum brotli2::CompressMode\">CompressMode</a>",synthetic:false,types:["brotli2::CompressMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"brotli2/struct.CompressParams.html\" title=\"struct brotli2::CompressParams\">CompressParams</a>",synthetic:false,types:["brotli2::CompressParams"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
